version: '3.7'

x-default: &default
  build:
    context: .
  env_file: .env
  tty: true
  stdin_open: true

services:
  web:
    <<: *default
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0" 
    volumes:
      - .:/app:rw
      - data-tmp:/app/tmp
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb 
  mongodb:
    image: mongo:2.2
    # container_name: mongo4
    restart: always
    ports:
      - '27017:27017'
      - '28017:28017'
  sidekiq:
    <<: *default
    command: /bin/sh -c "bundle exec sidekiq -e development"
    depends_on:
      - redis
    volumes:
      - .:/app:rw
      - data-tmp:/app/tmp
    links:
      - mongodb
      - redis
  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - data-redis:/data
  # # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #     - 3000:3000
  #   volumes:
  #     - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./docker/development/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - web

volumes:
  data-tmp:
    driver: local
  data-redis:
    driver: local
