monthly_vacation_job:
  cron: '0 12 1 * *'  # At 12:00 on day-of-month 1.
  class: 'VacationWorker'

regular_sick_leave_job:
  cron: '0 12 1 */3 *' # At 12:00 on day-of-month 1 in every 3rd month
  class: 'SickLeaveWorker'

yearly_holiday_job:
  cron: '0 0 * 1 *' # At 00:00 in January.
  class: 'HolidayYearlyWorker'

monthly_holiday_job:
  cron: '0 0 1 * *' # At 00:00 on day-of-month 1.
  class: 'HolidayMonthlyWorker'

daily_reports_job:
  cron: '0 0 * * 1-5' #  At 00:00 on every day-of-week from Monday through Friday.
  class: 'ReportsWorker'

